#!/usr/bin/env python
import ansi,sys

# Set up whatever ANSI attribute-foreground-background combo the suer wants.
if len(sys.argv)>1:
  a,f,b=parseColor(' '.join(sys.argv[1:]))
  c=color(a,f,b)
  sys.stdout.write(c)

# Write stdin to stdout if stdin a file or a pipe.
if not sys.stdin.isatty():
  for line in sys.stdin:
    sys.stdout.write(line)

# Be sure to normalize the terminal if we messed with it at the start.
if len(sys.argv)>1:
  sys.stdout.write(norm)
