#!/usr/bin/env python
import ansi,sys

# Set up whatever ANSI attribute-foreground-background combo the user wants.
if len(sys.argv)>1:
  c=ansi.Color(' '.join(sys.argv[1:]))
  sys.stdout.write(str(c))

# Write stdin to stdout if stdin a file or a pipe.
if not sys.stdin.isatty():
  for line in sys.stdin:
    sys.stdout.write(line)

# Be sure to normalize the terminal if we messed with it at the start.
if len(sys.argv)>1:
  sys.stdout.write(str(ansi.norm))
