#!/usr/bin/env python3
import sys

n=len(sys.argv) # Get the number of arguments.
w=len(str(n-1)) # Get the maximum number of digits in an argument number.
for i in range(n):
  print(f"{i:{w}}: >{sys.argv[i]}<")
