#!/usr/bin/env python
import optparse,os,sys
from math import ceil
from OptionParserFormatters import IndentedHelpFormatterWithNL

# default_padding[radix]=number of digits to allow for.
default_padding={
  2:8,
  8:3,
  10:3,
  16:2
}

column_breaks={
  2:4,
  8:4,
  10:5,
  16:4
}

# Set up for outputting an ASCII table.
character3=[
  'NUL','SOH','STX','ETX','EOT','ENQ','ACK','BEL',
  ' BS','TAB',' LF',' VT',' FF',' CR',' SO',' SI',
  'DLE','DC1','DC2','DC3','DC4','NAK','SYN','EBT',
  'CAN',' EM','SUB','ESC',' FS',' GS',' RS',' US'
]
for ch in range(32,127):
  character3.append('  '+chr(ch))
character3.append('DEL')

# Handle command line options.
op=optparse.OptionParser(
  add_help_option=False,
  formatter=IndentedHelpFormatterWithNL(2,8),
  usage="%prog [OPTIONS] [string]",
  description="Description: Read text from standard input and/or the command line argument(s), and output the ASCII value of each character in the given or default radix."
)
op.add_option('--radix','-r',dest='radix',action='store',type='int',default=16,help="Set the base to use when giving ASCII values for characters. The valid range is from 2 to 36. (default: %default)")
op.add_option('-b',dest='radix',action='store_const',const=2,help="Binary (--radix 2)")
op.add_option('-d',dest='radix',action='store_const',const=10,help="Decimal (--radix 10)")
op.add_option('-h',dest='radix',action='store_const',const=16,help="Hexadecimal (--radix 16)")
op.add_option('-o',dest='radix',action='store_const',const=8,help="Octal (--radix 8)")
op.add_option('--pad',dest='pad',action='store',type='int',default=0,help="Pad with leading zeros to make numeric values occupy this many characters (not counting any prefix). (default: %default)")
op.add_option('--prefix','-p',action='store_true',default=False,help="Prefix each numeric character value with notation indicating the base being used.")
op.add_option('-t',dest='value_only',action='count',default=0,help="How terse would you like the output to be? -t suppresses the output each corresponding character, giving one numeric value per line. -tt gives one line with values separated by spaces. -ttt outputs all values on one line with nothing between them.")
op.add_option('--table',dest='table',action='store_true',help="Rather than translating standard input and the command line into ASCII on standard output, just wright an ASCII table to standard output.")
op.add_option('--help',dest='help',action='store_true',default=False,help="Show this usage message.")
try:
  opt,args=op.parse_args()
except Exception,e:
  print >>sys.stderr,str(e)
  sys.exit(2)
if opt.help:
  op.print_help()
  sys.exit(0)
if opt.radix<2 or opt.radix>36:
  op.print_help()
  sys.exit(2)
if opt.prefix:
  if opt.radix==2: opt.prefix='0b'
  elif opt.radix==8: opt.prefix='0'
  elif opt.radix==10: opt.prefix=''
  elif opt.radix==16: opt.prefix='0x'
  else: opt.prefix='%db'%opt.radix
else:
  opt.prefix=''
if opt.value_only:
  if opt.value_only==1: opt.delimiter='\n'
  elif opt.value_only==2: opt.delimiter=' '
  else: opt.delimiter=''

# Get the input from stdin and/or command line.
instr=''
if not sys.stdin.isatty():
  instr+=os.fdopen(sys.stdin.fileno(),'rb').read()
if args:
  instr+=' '.join(args)

digits='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
def based_integer(n,b,prefix='',pad=0):
  """Return a string expressing the integer n in base b, optionally
  following the given prefix string."""

  chars=[]
  sign=1
  if n<0:
    sign=-1
  elif n==0:
    chars=digits[:1]
  else:
    sign=1
  n*=sign
  while n>0:
    chars.insert(0,digits[n%b])
    n/=b
  if sign==-1:
    chars.insert('-')
  if len(chars)<pad:
    prefix+=digits[0]*(pad-len(chars))
  return prefix+''.join(chars)

if opt.table:
  if opt.radix not in default_padding:
    sys.stderr.write("I'm really not set up to output an ASCII table with radix=%d.\n"%opt.radix)
    sys.exit(1)
  if default_padding[opt.radix]==2:
    prefix='  '
  else:
    prefix=' '
  if opt.radix==2:
    cw=8
    columns=8
  else:
    cw=3
    columns=opt.radix
  sys.stdout.write(' '*default_padding[opt.radix]+prefix)
  for col in range(columns):
#   if col%column_breaks[opt.radix]==0:
#     sys.stdout.write('  ')
    sys.stdout.write(based_integer(col,opt.radix,prefix,default_padding[opt.radix]))
  for row in range(int(ceil(128.0/columns))):
    sys.stdout.write('\n'+based_integer(row*opt.radix,opt.radix,prefix,default_padding[opt.radix]))
    for col in range(columns):
      ch=row*columns+col
      if ch>=len(character3):
        break
#     if col%column_breaks[opt.radix]==0:
#       sys.stdout.write('  ')
      sys.stdout.write(' '+('%*s'%(cw,character3[ch])))
  sys.stdout.write('\n')
else:
  if opt.value_only:
    print opt.delimiter.join([
      based_integer(ord(ch),opt.radix,opt.prefix,opt.pad) for ch in instr
    ])
  else:
    for ch in instr:
      n=based_integer(ord(ch),opt.radix,opt.prefix,opt.pad)
      print '%r: %s'%(ch,n)
