#!/usr/bin/env python3

import math,sys

def usage():
  print('usage: %s n ...\nwhere n is an integer whose factors are to be found.'%sys.argv[0])
  sys.exit(1)

# Get the integer value(s) whose factors we are to find.
if len(sys.argv)<2:
  usage()
try:
  sys.argv[1:]=[int(x) for x in sys.argv[1:]]
except:
  usage()

for n in sys.argv[1:]:
  # Find all factors for this value of n.
  factors=set([])
  x=1.0
  limit=int(round(math.sqrt(n)))
  while x<=limit:
    x+=1
    f,i=math.modf(n/x)
    if f==0.0:
      factors.add(int(x))
      factors.add(int(i))
  print('%d: %s'%(n,' '.join(['%s'%i for i in sorted(list(factors))])))
