#!/usr/bin/env python3

import time,unittest
from timeout import Timeout

class TimeoutUnitTest(unittest.TestCase):

  def testTimeout1(self):
    with Timeout(1):
      x=5
    self.assertEqual(x,5)

  def testTimeout2(self):
    try:
      with Timeout(1):
        time.sleep(2)
        self.assertTrue(False,mnsg="Failed to time out!")
    except Timeout.Error as e:
      self.assertEqual(str(e),"Timed out after 1 second.")

  def testTimeout3(self):
    try:
      with Timeout(2):
        time.sleep(3)
        self.assertTrue(False,mnsg="Failed to time out!")
    except Timeout.Error as e:
      self.assertEqual(str(e),"Timed out after 2 seconds.")

  def testTimeout4(self):
    try:
      with Timeout(1,"Took too long!"):
        time.sleep(3)
        self.assertTrue(False,mnsg="Failed to time out!")
    except Timeout.Error as e:
      self.assertEqual(str(e),"Took too long!")

unittest.main()
